# Generated by Django 3.0.7 on 2021-09-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
