# Generated by Django 3.0.7 on 2021-09-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_auto_20210926_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='plan_name',
        ),
    ]
