# Generated by Django 3.0.7 on 2021-09-26 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_auto_20210926_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('plan_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.Category')),
            ],
        ),
    ]
