# Generated by Django 3.0.7 on 2021-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternetOutage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_description', models.TextField()),
                ('notice_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
