# Generated by Django 3.0.7 on 2021-09-27 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_orderplan'),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internet.Category'),
        ),
    ]
